#!/bin/zsh -e

function() {
	FPATH=$FPATH:$HOME/.utils/tools

	for file in $HOME/.utils/tools/*(N-.); do
    func=$(basename $file)
    autoload -Uz $func
    zle -N $func
  done
}

function utils-entory-point(){}

