#!/bin/zsh -e

function() {
    FPATH=$FPATH:$HOME/.zsh-utils/tools

    for file in $HOME/.zsh-utils/tools/*(N-.); do
        func=$(basename $file)
        autoload -Uz $func
        zle -N $func
    done
}

function zsh-utils(){}

