#!/bin/zsh -e

function pco() {
    readonly _target_branch=$(git branch | peco --prompt "git branch>" | head -n 1 | sed -e "s/^\*\s*//g" | tr -d " ")

    # select a condition from the menu and execute the action
    if [ -z $_target_branch ]; then
        echo "Canceled or something went wrong" >&2
        return 1
    else
        git checkout $_target_branch
    fi
}
