#!/bin/zsh -e

#
# pe is a function that enable to enter the selected container
#
function pe() {
    local _target_container="$(docker ps | peco --prompt "docker container>" | cut -d " " -f 1)"
    if [ -n $_target_container ]; then
        _exec-command "docker exec -it $_target_container /bin/bash"
    else
        echo "Canceled or something went wrong" >&2
        return 1
    fi
}

