#!/bin/zsh -e

# Show 256 colors
for color in {0..255} ; do
    printf "\x1b[48;5;%sm%3d\e[0m " "$color" "$color"
    if (( color == 15 )) || (( color > 15 )) && (( (color-15) % 16 == 0 )); then
        printf "\n";
    fi
done
